# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-aNsMvWSaFzrDoQnKv1Ix_NwzQGHIHdD
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="vooEoyUfTb9l6b3Badjb")
project = rf.workspace("dogandcat-tojsg").project("dog-and-cat-eu2ol")
version = project.version(1)
dataset = version.download("yolov8")

!pip install ultralytics -q
import ultralytics

!yolo task=detect mode=train model=yolov8m.pt data=/content/dog-and-cat-1/data.yaml epochs=70 imgsz=640